name: gharelu
description: A new Flutter project.

version: 1.0.0+0

environment:
  sdk: ^3.8.1

dependencies:
  auto_route: ^10.1.2
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^2.0.0-dev.9
  image_cropper: ^9.1.0
  image_picker: ^1.0.2
  json_annotation: ^4.4.0
  logger: ^2.0.1
  permission_handler: ^12.0.1
  url_launcher: ^6.1.5
  carousel_slider: ^5.0.0
  chat_bubbles: ^1.3.0
  dartz: ^0.10.1
  flutter_map: ^8.2.1
  dio: ^5.3.2
  dotted_border: ^3.1.0
  firebase_storage: ^13.0.0
  calendar_timeline: ^1.0.5
  # khalti_flutter: ^3.0.0
  webview_flutter: ^4.0.1
  lottie: ^3.1.3
  awesome_notifications: ^0.10.1
  flutter_hooks: ^0.21.3+1
  algolia_helper_flutter: ^1.1.0
  flutter_typeahead: ^5.2.0
  dropdown_button2: ^2.3.7
  flutter_native_splash: ^2.2.16
  get_it: ^8.0.2
  flutter_dotenv: ^6.0.0
  frontend_server_client: ^4.0.0
  velocity_x: ^4.2.1

dependency_overrides:
  intl: any
  win32: ^5.9.0
  algolia_client_core: 1.27.1
  algolia_client_insights: 1.27.1
  algolia_client_search: 1.27.1
  algoliasearch: 1.27.1

dev_dependencies:
  auto_route_generator: ^10.2.4
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  # flutter_osm_plugin: ^0.37.1
  flutter_launcher_icons: ^0.14.1
  freezed: ^3.2.0
  json_serializable: ^6.9.0
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/src/core/assets/
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/gharelu_logo.jpg"
  min_sdk_android: 21

flutter_native_splash:
  color: "#7210FF"
  image: "assets/images/gharelu_logo.jpg"
