name: gharelu
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.3.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^4.0.0
  equatable: ^2.0.3
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.5.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^1.0.3
  image_cropper: ^2.0.3
  image_picker: ^0.8.5+3
  json_annotation: ^4.4.0
  logger: ^1.1.0
  permission_handler: ^10.0.0
  url_launcher: ^6.1.5
  velocity_x: ^3.5.1
  carousel_slider: ^4.1.1
  chat_bubbles: ^1.3.0
  dartz: ^0.10.1
  flutter_map: ^2.2.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2

dev_dependencies:
  auto_route_generator: ^4.2.0
  build_runner: ^2.1.10
  flutter_gen_runner: ^4.3.0
  # flutter_osm_plugin: ^0.37.1
  freezed: ^2.0.3
  json_serializable: ^6.2.0
  very_good_analysis: ^3.0.1

dependency_overrides:
  ? analyzer
  ? meta

flutter_gen:
  output: lib/src/core/assets/
  integrations:
    flutter_svg: true

flutter:

  
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/